{
  "generated_at": "2026-05-04T10:30:30.247705",
  "weekly_fixed_costs": 3500.0,
  "current_weekly_profit": 9561.0,
  "optimised_weekly_profit": 11039.28,
  "weekly_improvement": 1478.28,
  "annual_improvement": 76870.45,
  "breakeven": {
    "total_weekly_cm": 13061.0,
    "total_weekly_revenue": 17340.0,
    "net_profit": 9561.0,
    "monthly_profit": 41399.13,
    "annual_profit": 497172.0,
    "total_weekly_covers": 1155,
    "avg_cm_per_cover": 11.31,
    "breakeven_covers": 309.51,
    "surplus_covers": 845.49,
    "safety_margin_pct": 73.2,
    "fixed_costs": 3500.0
  },
  "items": [
    {
      "id": 1,
      "name": "Wagyu Burger",
      "category": "Mains",
      "cost": 8.5,
      "current_price": 24.0,
      "optimal_price": 32.5,
      "weekly_qty": 120,
      "elasticity": -1.2,
      "cm_per_unit": 15.5,
      "margin_pct": 64.6,
      "weekly_cm_curr": 1860.0,
      "weekly_cm_opt": 2000.68,
      "quadrant": "Puzzle"
    },
    {
      "id": 2,
      "name": "Truffle Pasta",
      "category": "Mains",
      "cost": 6.2,
      "current_price": 22.0,
      "optimal_price": 29.75,
      "weekly_qty": 85,
      "elasticity": -1.0,
      "cm_per_unit": 15.8,
      "margin_pct": 71.8,
      "weekly_cm_curr": 1343.0,
      "weekly_cm_opt": 1479.63,
      "quadrant": "Puzzle"
    },
    {
      "id": 3,
      "name": "Caesar Salad",
      "category": "Starters",
      "cost": 2.8,
      "current_price": 14.0,
      "optimal_price": 19.0,
      "weekly_qty": 200,
      "elasticity": -0.8,
      "cm_per_unit": 11.2,
      "margin_pct": 80.0,
      "weekly_cm_curr": 2240.0,
      "weekly_cm_opt": 2532.73,
      "quadrant": "Plow Horse"
    },
    {
      "id": 4,
      "name": "Espresso Martini",
      "category": "Drinks",
      "cost": 1.9,
      "current_price": 16.0,
      "optimal_price": 21.5,
      "weekly_qty": 180,
      "elasticity": -0.6,
      "cm_per_unit": 14.1,
      "margin_pct": 88.1,
      "weekly_cm_curr": 2538.0,
      "weekly_cm_opt": 2961.68,
      "quadrant": "Star"
    },
    {
      "id": 5,
      "name": "Lava Cake",
      "category": "Desserts",
      "cost": 2.4,
      "current_price": 12.0,
      "optimal_price": 16.25,
      "weekly_qty": 90,
      "elasticity": -1.1,
      "cm_per_unit": 9.6,
      "margin_pct": 80.0,
      "weekly_cm_curr": 864.0,
      "weekly_cm_opt": 892.8,
      "quadrant": "Dog"
    },
    {
      "id": 6,
      "name": "House Wine",
      "category": "Drinks",
      "cost": 3.2,
      "current_price": 11.0,
      "optimal_price": 14.75,
      "weekly_qty": 250,
      "elasticity": -0.9,
      "cm_per_unit": 7.8,
      "margin_pct": 70.9,
      "weekly_cm_curr": 1950.0,
      "weekly_cm_opt": 2223.13,
      "quadrant": "Plow Horse"
    },
    {
      "id": 7,
      "name": "Grilled Salmon",
      "category": "Mains",
      "cost": 9.8,
      "current_price": 28.0,
      "optimal_price": 37.75,
      "weekly_qty": 70,
      "elasticity": -1.3,
      "cm_per_unit": 18.2,
      "margin_pct": 65.0,
      "weekly_cm_curr": 1274.0,
      "weekly_cm_opt": 1326.85,
      "quadrant": "Puzzle"
    },
    {
      "id": 8,
      "name": "Garlic Bread",
      "category": "Starters",
      "cost": 0.8,
      "current_price": 7.0,
      "optimal_price": 9.5,
      "weekly_qty": 160,
      "elasticity": -0.7,
      "cm_per_unit": 6.2,
      "margin_pct": 88.6,
      "weekly_cm_curr": 992.0,
      "weekly_cm_opt": 1121.77,
      "quadrant": "Plow Horse"
    }
  ]
}
